CREATE DATABASE PWEB2;
USE PWEB2;

CREATE TABLE usu(
    nome VARCHAR(100) NOT NULL,
    usu VARCHAR(100) NOT NULL,
    email VARCHAR(60) NOT NULL,
    senha VARCHAR(32) NOT NULL, 
    CONSTRAINT PRIMARY KEY(usu, senha)
);